services:
  - type: web
    name: query-retrieval-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app" # Or whatever your app entry point is
    runtime: python3.10
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
